### ISSUE TITLE
[IMPROVEMENT] Convert to the CafeAPI

### ISSUE THREAD

**Issue by beanbeanjuice** [beanbeanjuice/cafeBot#408]
**__Describe the Improvement__**
Right now, all the code is being run ON `cafeBot`. As of right now, this can slow down the bot significantly doing meaningless calculations and running meaningless code. Running and moving to an API will help cafeBot improve in the future, and also help potential new users be able to code on `cafeBot` using the `CafeAPI`.

# TODO:
- [x] ServeWords
- [x] Welcomes
- [x] Voice Binds
- [x] Raffles
- [x] Polls
- [x] Minigames
- [x] Interactions
- [x] Guilds
- [x] Twitch
- [x] Counting
- [x] Codes
- [x] cafeBot Information
- [x] Cafe Users
- [x] Birthdays
- [x] beanCoin Donation Users
- [x] Interaction Pictures

# Checklist:

- [x] I have checked for similar issues.
- [x] This is an improvement request, not a bug report or feature request.

**Comment by beanbeanjuice** [comment]
One of the images for the `cry` interaction does not work.
